# Compulsory Task

In this compulsory task you will use pandas to select data from a dataset and explain the data retrieved for a given line of code.

In [1]:
import pandas as pd

You will use the same `balance.txt` dataset used in the example Jupyter notebook. Remember to ensure it is in the same folder as this notebook.

In [ ]:
df = pd.read_csv('balance.txt',sep=' ')

1. Write the code that performs the action described in the following statements.

In [ ]:
# Select the 'Limit' and 'Rating' columns of the first five observations
df[['Limit', 'Rating']].loc[0:4]

In [ ]:
# Select the first five observations with 4 cards
df[df['Cards'] == 4].head()

In [ ]:
# Sort the observations by 'Education'. Show users with a high education value first.
df.sort_values(by='Education', ascending=False)

2. Write a short explanation in the form of a comment for the following lines of code. For example:  
```
# Selects the first 5 rows, and all of the columns for those rows.
df.iloc[:5,:]
```

In [ ]:
# This code displays all rows and all columns in the dataset.
df.iloc[:,:]

In [ ]:
# This code displays rows starting from the 5th row to the last row, and columns starting from the 
# 5th column to the last column
df.iloc[5:,5:]

In [ ]:
# This code displays all the rows under column 0(Balance)
df.iloc[:,0]

In [ ]:
# This code displays row 9 and all its corresponding columns 
df.iloc[9,:]